### ISSUE TITLE
Repulsor can't deflect projectiles from other mods

### ISSUE THREAD

**Issue by Syampuuh** [Lewisk3/HaloDoom_GZDoomVersion#13]
I have tested with [Pandemonium](https://forum.zdoom.org/viewtopic.php?t=60984), [Touhou Enemies](https://forum.zdoom.org/viewtopic.php?f=43&t=65432), and one of the dozen Project Brutality monsters-only packs floating around out there. The repulsor seems to only behave correctly with projectiles that are reskins of vanilla projectiles, ie. Touhou Enemies' imps still fire a standard DoomImpBall. Anything else doesn't want to work.

I ran this by the Pandemonium devs in the hopes they could point out some difference between theirs and vanilla projectiles or otherwise determine why the repulsor won't work with them, but as best they could tell it *should* work with any projectile, so I'm pretty stumped. The only immediate difference I've noticed while digging through Pandemonium in particular is that their projectiles are being shot with A_SpawnProjectile instead of SpawnMissile, but I don't know enough myself to know if that's significant or not and what other differences there may be.

Quick edit: I was able to work around this by removing
`if(act.damage <= 0 && !haloproj && !haloslowproj) continue;`
from the repulsor. This has the extra Ultrakill side effect of letting me punch my own shots, which is funny enough to be an acceptable caveat for myself at least. Oddly just removing any of the individual conditions didn't cut it? But I'll just chalk that up to just me not actually knowing what I'm doing.

**Comment by Lewisk3** [comment]
I think you're possibly using an outdated version of the mod. 
The above line of code was changed to this - https://github.com/Lewisk3/HaloDoom_GZDoomVersion/blob/Local_DEV/ZScript/Items/powerup_base.zsc#L742 `IsZeroDamage()` is now used instead, which should solve this issue.

Be sure to check this branch for the most up-to-date code - https://github.com/Lewisk3/HaloDoom_GZDoomVersion/tree/Local_DEV (Code -> Download as ZIP). 

P.S You should be able to parry your own shots with that check in place, actually. This was originally a bug, but was decided by the dev team to become a feature due to the ultra-kill resemblance. 

Let me know if this solves your issue, if it does then I'll close this.

**Comment by Syampuuh** [comment]
Ah, yeah that would fit then, I was on the master release. This does it, thanks. 👌
